const S = (pages, note = "") => ({ sourceId: "L02", file: "New Slides 2(2).pdf", pdfPages: pages, note });
const P = (id, prompt, hint, answer) => ({ id, prompt, hint, answer });

export const lecture2 = {
  id: "L02", title: "消费者问题", originalTitle: "Consumer Problem", status: "ready", pptPages: 39,
  description: "竞争预算、需求、弹性、WARP、补偿需求法则与 Slutsky 矩阵。",
  lessons: [
    { id:"L02-M01",sectionId:"L02-S01",title:"商品向量与竞争预算",minutes:10,status:"ready",sourceRefs:[S([1,2,3,4])],bridge:"第一讲把选择集合当作抽象对象；现在把它具体化为带价格和财富的预算集，并逐一说明向量、分量、点积和预算边界。",why:"把抽象选择集换成有价格与财富的商品空间，之后所有需求结论都从 p·x≤w 的几何出发。",wakeup:"点积 p·x 是总支出；价格向量 p 是预算超平面的法向量。",concept:["商品束写成 x=(x₁,…,x_L)：最后一项是下标 L 的分量，不是 x 的 L 次幂。消费集是非负正交域的一部分；竞争预算集用价格 p 和财富 w 标记为 B_{p,w}。所有商品被当作 goods 时通常 p≫0。","预算边界记为 H_{p,w}。两商品下斜率为 -p₁/p₂；改变共同计价单位不会改变集合。"],formal:[{tex:"x=(x_1,\\ldots,x_L)\\in X\\subseteq\\mathbb{R}_+^L"},{tex:"B_{p,w}=\\{x\\in X:p\\cdot x\\le w\\}"},{tex:"H_{p,w}=\\{x\\in\\mathbb{R}^L:p\\cdot x=w\\}"}],visual:{type:"budget",title:"价格和财富怎样移动预算线",caption:"阴影为可负担集合。拖动价格与财富，观察截距和斜率分别怎样变化。"},demo:{prompt:"p=(2,1),w=6 时，(2,2) 是否可负担？",steps:["支出 2×2+1×2=6。","等于财富，所以位于预算线上且可负担。"]},practice:P("P-L02-M01","p=(3,2),w=12。求两轴截距并解释法向量。","令另一商品为 0。","截距为 (4,0)、(0,6)；p=(3,2) 与预算线正交，给出支出增加最快的方向。") },
    { id:"L02-M02",sectionId:"L02-S02",title:"需求对应、零次齐次与瓦尔拉斯法则",minutes:12,status:"ready",sourceRefs:[S([5,6,7])],why:"需求可能多值；零次齐次与预算用尽是需求理论最常用的两个基础限制。",concept:["Walras 需求对应 x(p,w) 给每个价格-财富对一组选择；只有单值时才称需求函数。竞争预算族与它组成选择结构。","零次齐次：x(αp,αw)=x(p,w)，因为预算集不变。瓦尔拉斯法则：每个被选束都满足 p·x=w；本讲先作假设，第三讲再由偏好条件推出。"],formal:["x(αp,αw)=x(p,w), α>0","p·x(p,w)=w"],demo:{prompt:"价格和财富都翻倍，为什么不是需求也翻倍？",steps:["约束 2p·x≤2w 与 p·x≤w 等价。","可选集合不变，所以零次齐次要求选择不变。"]},practice:P("P-L02-M02","若只把财富翻倍而价格不变，零次齐次能否直接判断需求？","齐次缩放要求哪些参数同步？","不能。零次齐次只约束 p 与 w 同比例变化；单独财富变化是财富效应。"),exerciseIds:["MWG-2.E.7"] },
    { id:"L02-M03",sectionId:"L02-S03",title:"财富效应与 Engel 路径",minutes:9,status:"ready",sourceRefs:[S([8,9])],why:"固定价格只改变财富，才能把正常品与劣等品的局部定义说清楚。",concept:["固定 p̄，Engel 函数是 w↦x(p̄,w)；其在商品空间的像是财富扩张路径。","第 ℓ 种商品在 (p,w) 正常若 ∂xℓ/∂w≥0，劣等若 <0。这是点上的局部性质；一件商品可在不同财富区间改变类型。"],formal:["D_w x=(∂x₁/∂w,…,∂xᴸ/∂w)ᵀ"],demo:{prompt:"x₁=w/(1+w) 是正常品吗？",steps:["导数为 1/(1+w)²。","w>0 时为正，所以在该域内正常，但增幅递减。"]},practice:P("P-L02-M03","x₂=4-w/10 在可行区间的财富效应是什么？","对 w 求导。","∂x₂/∂w=-1/10<0，所以在该区间是劣等品；仍需检查数量非负的定义域。") },
    { id:"L02-M04",sectionId:"L02-S03",title:"价格效应、需求曲线与 offer curve",minutes:10,status:"ready",sourceRefs:[S([10,11])],why:"需求曲线画价格对数量，offer curve 画需求束在商品空间的轨迹，坐标不同不能混用。",concept:["固定其他价格 p₋ₖ 与财富 w，考察 pₖ↦x(p,w)。Dₚx 的第 (ℓ,k) 元是 ∂xℓ/∂pₖ。","自身价格效应 ∂xℓ/∂pℓ>0 时称 Giffen；这说的是未补偿的普通需求，不等于补偿替代效应为正。"],formal:["Dₚx=[∂xℓ/∂pₖ]_{L×L}"],demo:{prompt:"为什么 offer curve 不是通常横轴数量、纵轴价格的需求曲线？",steps:["offer curve 的点是完整商品束 x。","其坐标轴是商品数量；价格只是沿曲线变化的参数。"]},practice:P("P-L02-M04","∂x₁/∂p₂ 表示什么？它能直接判定商品 1 是 Giffen 吗？","Giffen 看哪个导数？","它是商品2价格对商品1需求的交叉价格效应；Giffen 看 ∂x₁/∂p₁，不能由交叉项判定。") },
    { id:"L02-M05",sectionId:"L02-S04",title:"Euler 公式与弹性加总",minutes:12,status:"ready",sourceRefs:[S([12,13,14])],why:"零次齐次的全局缩放不变，可微时会变成一条局部导数恒等式。",concept:["对每个需求分量 xℓ，把变量看作 (p₁,…,pᴸ,w)。零次齐次的 Euler 公式给 ∑ₖ(∂xℓ/∂pₖ)pₖ+(∂xℓ/∂w)w=0。","除以 xℓ 后得到弹性式 ∑ₖεℓk+εℓw=0。它描述所有价格与财富同百分比变化时总效应为零。"],formal:["Dₚx·p+D_wx·w=0_L","∑ₖ εℓk+εℓw=0"],demo:{prompt:"为何导数要乘变量水平？",steps:["同百分比变化意味着 dpₖ=pₖdt、dw=w dt。","乘水平后各项对应同一比例冲击的方向导数。"]},practice:P("P-L02-M05","若某商品的财富弹性为 1/2，所有价格弹性之和是多少？","使用弹性加总等式。","∑ₖεℓk=-εℓw=-1/2。") },
    { id:"L02-M06",sectionId:"L02-S05",title:"Cournot 与 Engel 加总",minutes:12,status:"ready",sourceRefs:[S([15,16])],why:"对瓦尔拉斯等式分别对价格和财富求导，会产生两条经常用于化简 Slutsky 矩阵的恒等式。",concept:["对 p·x(p,w)=w 关于 pₖ 求导，乘积规则给 ∑ℓpℓ∂xℓ/∂pₖ+xₖ=0（Cournot 加总）。","关于 w 求导给 ∑ℓpℓ∂xℓ/∂w=1（Engel 加总）。前者每个 k 一条，后者是一条标量等式。"],formal:["pᵀDₚx+xᵀ=0ᵀ","pᵀD_wx=1"],demo:{prompt:"Cournot 式为什么多出 xₖ？",steps:["求导 pℓxℓ 时价格和需求都可能变。","∂pℓ/∂pₖ 只在 ℓ=k 时为1，留下 xₖ。"]},practice:P("P-L02-M06","写出二商品下对 p₁ 求导的完整乘积式。","两项都用乘积法则。","x₁+p₁∂x₁/∂p₁+p₂∂x₂/∂p₁=0。"),exerciseIds:["MWG-2.E.3"] },
    { id:"L02-M07",sectionId:"L02-S06",title:"把竞争预算下的 WARP 写成不等式",minutes:11,status:"ready",sourceRefs:[S([17,18])],why:"WARP 在预算数据里不是抽象集合句子，而是‘旧束在新价格下买得起，则反向不能也买得起’。",concept:["令 x=x(p,w)、x′=x(p′,w′)。若 p·x′≤w，表示新选择在旧预算可负担。只要 x′≠x，WARP 要求 p′·x>w′：旧选择在新预算必须严格不可负担。","若两边都可负担且选择不同，就形成相互揭示严格偏好，违反 WARP。"],formal:["p·x′≤w 且 x′≠x ⇒ p′·x>w′"],demo:{prompt:"两期数据怎样快速检查 WARP？",steps:["用旧价格给新束计价，检查是否≤旧财富。","若是，再用新价格给旧束计价；若也≤新财富且束不同，则违规。"]},practice:P("P-L02-M07","p=(1,1),w=4,x=(3,1)；p′=(2,1),w′=5,x′=(2,1)。是否违规？","做两次交叉计价。","p·x′=3≤4；p′·x=7>5，所以没有形成反向可负担，不违反这两期 WARP。"),exerciseIds:["MWG-2.F.6"] },
    { id:"L02-M08",sectionId:"L02-S07",title:"Slutsky 财富补偿",minutes:9,status:"ready",sourceRefs:[S([19,20])],why:"价格改变同时带来替代与实际财富效应；Slutsky 补偿把财富调到刚好买得起原束。",concept:["初始 x=x(p,w)，价格变为 p′ 后设 w′=p′·x。于是原束在新预算边界上。财富调整量 Δw=(p′-p)·x=Δp·x。","补偿需求法则：在零次齐次、瓦尔拉斯法则下，WARP 等价于 Δp·Δx≤0；选择改变时严格小于0。"],formal:["w′=p′·x(p,w)","(p′-p)·(x′-x)≤0"],demo:{prompt:"只提高商品1价格 Δp₁，补偿多少财富？",steps:["其他价格不变，所以 Δw=Δp₁x₁。","补偿按原消费量 x₁ 计算，不按新需求。"]},practice:P("P-L02-M08","初始 x=(2,3)，Δp=(1,-.5)。Slutsky 补偿量是多少？","算点积。","Δw=1×2+(-.5)×3=0.5。") },
    { id:"L02-M09",sectionId:"L02-S08",title:"WARP 推出补偿需求法则",minutes:13,status:"ready",sourceRefs:[S([21,22,23])],why:"核心代数把 Δp·Δx 改写成‘新束在旧价格下超出多少财富’，再让 WARP 决定符号。",concept:["记 x、x′ 为补偿前后需求。展开 (p′-p)·(x′-x)，用 p·x=w、p′·x′=w′、p′·x=w′，可化为 w-p·x′。","原束在新预算可负担且被选；若 x′≠x，WARP 要求新束在旧预算不可负担，即 p·x′>w，所以 w-p·x′<0。"],proof:{known:"瓦尔拉斯法则；w′=p′·x；WARP。",goal:"(p′-p)·(x′-x)≤0，变化时严格。",steps:["展开四个点积。","代入 p′·x′=w′、p′·x=w′、p·x=w，得到 w-p·x′。","若 x′=x，表达式为0。","若不同，WARP 给 p·x′>w，因此严格小于0。"],assumptions:"补偿方向是从原情形到新价格，财富按原束调整。"},practice:P("P-L02-M09","证明中哪个等式来自补偿定义，哪个来自新需求的瓦尔拉斯法则？","两者都等于 w′，但对象不同。","p′·x=w′ 来自 Slutsky 补偿；p′·x′=w′ 来自新情形的瓦尔拉斯法则。"),review:{id:"R-L02-01",prompt:"Slutsky 补偿把新财富设成什么？为什么？",answer:"w′=p′·x(p,w)，使原消费束在新价格下恰好仍可购买。"} },
    { id:"L02-M10",sectionId:"L02-S08",title:"从补偿变化推广到所有 WARP 比较",minutes:20,status:"ready",sourceRefs:[S([24,25,26,27,28,29])],why:"反向证明最难的一步是构造中间价格，把两个互相可负担但未补偿的情形转成一个补偿比较。",concept:["补偿需求法则先直接排除补偿变化中的 WARP 违规。要覆盖一般变化，反设两个不同束互相可负担。若有一个交叉支出等号，已是补偿变化。","若两边都严格可负担，把价格在 p′ 与 p″ 之间凸组合，选择 α 使两个旧束在中间价格 p̄ 下支出相同。下面把权重、预算差和最终矛盾逐项算完。"],proof:{known:"瓦尔拉斯法则；所有补偿变化满足 WARP；不同需求束 x′、x″ 在彼此预算中都严格可负担。",goal:"由反设构造一对补偿变化并违反 WARP，从而证明一般 WARP。",steps:["令 d=x″−x′。互相严格可负担给 A=p′·d<0 与 B=p″·d>0。A、B 异号是选中间价格的输入。","取 α=B/(B−A)。因为 B>0 且 B−A>B，所以 0<α<1；定义 p̄=αp′+(1−α)p″。直接代入得 p̄·d=αA+(1−α)B=0。","令 w̄=p̄·x′=p̄·x″，并令 x̄=x(p̄,w̄)。瓦尔拉斯法则给 p̄·x̄=w̄，因此两个旧束与中间需求都在同一中间预算边界。","计算加权预算余量：α[w′−p′·x̄]+(1−α)[w″−p″·x̄]。用 w′=p′·x′、w″=p″·x″，再加减共同值 w̄，可把它化成 αp′·(x′−x̄)+(1−α)p″·(x″−x̄)。","若该加权和不为正，则两个原预算余量都不可能有正项。但利用 x′、x″ 互相严格可负担与 p̄·x′=p̄·x″ 可得加权和严格为正；故至少一个原预算对 x̄ 有严格余量。","不妨 w′−p′·x̄>0，即中间需求 x̄ 在原预算 (p′,w′) 中严格可负担，而原需求 x′ 在中间预算边界。若 x̄=x′，严格余量立即与 p′·x′=w′ 矛盾；故两束不同。","于是从原预算到中间预算是一组补偿比较：x′ 在中间预算可负担且被替代为 x̄，而 x̄ 又在原预算严格可负担。这与‘所有补偿变化满足 WARP’矛盾。另一原预算有正余量时论证完全对称。"],assumptions:"权重构造使用 A<0<B；瓦尔拉斯法则把 w′、w″ 和 w̄ 写成支出；最后严格余量保证束不同并给出 WARP 所需的严格冲突。"},practice:P("P-L02-M10","构造 p̄ 的唯一目的是什么？","看两个旧束在 p̄ 下的支出。","让 p̄·x′=p̄·x″，从而同一中间财富能让两个旧束都在边界，制造补偿比较。") },
    { id:"L02-M11",sectionId:"L02-S09",title:"从全微分得到 Slutsky 矩阵",minutes:13,status:"ready",sourceRefs:[S([30,31,32,33,34])],why:"把有限补偿需求法则局部化，就得到价格变化方向上的二次型与 Slutsky 矩阵。",concept:["全微分 dx=Dₚx dp+D_wx dw。Slutsky 补偿的一阶式 dw=xᵀdp，代入得 dx=[Dₚx+D_wx xᵀ]dp。","定义 S=Dₚx+D_wx xᵀ；元素 sℓk=∂xℓ/∂pₖ+(∂xℓ/∂w)xₖ。第一项是普通价格效应，第二项补回购买原 xₖ 所需财富的财富效应。"],formal:["S(p,w)=Dₚx+D_wx·xᵀ","sℓk=∂xℓ/∂pₖ+(∂xℓ/∂w)xₖ"],demo:{prompt:"为什么 D_wx xᵀ 是 L×L？",steps:["D_wx 是 L×1 列向量。","xᵀ 是 1×L 行向量，外积得到 L×L。"]},practice:P("P-L02-M11","s₁₂ 的经济含义是什么？","价格2变1单位，同时补偿多少财富？","商品2价格小幅上升1单位，同时补偿 x₂ 单位财富时，商品1需求的一阶变化。") },
    { id:"L02-M12",sectionId:"L02-S10",title:"负半定只限制补偿方向",minutes:12,status:"ready",sourceRefs:[S([35,36,37])],why:"WARP 推出 S 负半定，但反方向不成立；零二次型甚至可能藏着非对称与 WARP 违规。",concept:["补偿需求法则的局部式是 dpᵀSdp≤0，所以 S 负半定。取只有第 ℓ 位为1的方向，立即得自身替代效应 sℓℓ≤0。","负半定只看二次型，而二次型看不到矩阵的反对称部分；因此 S 负半定不能单独推出 WARP，也不能推出 S 对称。课件三商品例就是反例。"],formal:["∀v, vᵀSv≤0 ⇒ S 负半定","sℓℓ≤0"],demo:{prompt:"为什么 vᵀSv 看不到反对称部分 A？",steps:["Aᵀ=-A。","标量 vᵀAv 的转置等于 vᵀAᵀv=-vᵀAv，只能为0。"]},practice:P("P-L02-M12","S=0 是否负半定、负定、对称？","分别检查 ≤0、<0 与转置。","零矩阵负半定且对称；不是负定，因为任意非零 v 的二次型仍为0。") },
    { id:"L02-M13",sectionId:"L02-S10",title:"pᵀS=0 与 Sp=0",minutes:13,status:"ready",sourceRefs:[S([38,39])],why:"Slutsky 矩阵在价格向量方向有左右零向量，分别由加总恒等式与零次齐次性闭合。",concept:["pᵀS=pᵀDₚx+(pᵀD_wx)xᵀ。Cournot 给第一项=-xᵀ，Engel 给 pᵀD_wx=1，所以相消为0ᵀ。","Sp=Dₚx p+D_wx(xᵀp)。瓦尔拉斯法则 xᵀp=w，再用 Euler 零次齐次式 Dₚx p+D_wx w=0，故 Sp=0。"],formal:["pᵀS=0ᵀ_L","Sp=0_L"],demo:{prompt:"左右零向量能否单靠 S 对称互推？",steps:["本讲尚未得到 S 对称。","必须分别用加总式和齐次式证明，不能偷用第三讲以后条件。"]},practice:P("P-L02-M13","证明 Sp=0 时，哪一步使用瓦尔拉斯法则？","观察外积项 (D_wx xᵀ)p。","把 xᵀp 替换为 w 使用了瓦尔拉斯法则。"),review:{id:"R-L02-02",prompt:"Slutsky 矩阵的两个组成项是什么？",answer:"普通价格导数 Dₚx，加上财富效应列向量与需求行向量的外积 D_wx xᵀ。"} },
    { id:"L02-M14",sectionId:"L02-S10",title:"综合检验：等量需求与零 Slutsky 矩阵",minutes:16,status:"ready",sourceRefs:[S([39],"配套 MWG 2.F.17 原题见原 PDF 63 / 印刷 39，公式已按图像核对")],why:"用一道完整原题把齐次、瓦尔拉斯、WARP 与矩阵性质放在同一条推理链中。",concept:["令 P=∑ℓpℓ，需求为 xₖ=w/P（每种商品相同）。价格与财富同倍缩放时比值不变；总支出 ∑ₖpₖw/P=w。","任意 Slutsky 补偿把新财富设成 p′·x=qP′，新需求仍为 q，因此补偿下束不变，满足 WARP。各元素 sℓk=-w/P²+(1/P)(w/P)=0。"],demo:{prompt:"零矩阵给出的四项判断是什么？",steps:["负半定：是。","负定：否。","对称：是。","补偿价格变化下需求一阶变化：零。"]},practice:P("P-L02-M14","若所有商品需求都相同为 q，Walras 法则怎样直接求出 q？","总支出是 q 乘价格总和。","q∑ℓpℓ=w，所以 q=w/(∑ℓpℓ)。"),exerciseIds:["MWG-2.F.17"] }
  ]
};

export const lecture2Exercises = [
 {id:"MWG-2.E.3",lectureId:"L02",lessonId:"L02-M06",number:"2.E.3",difficulty:"B",status:"ready",original:"Use Propositions 2.E.1 to 2.E.3 to show that p·Dₚx(p,w)·p = -w. Interpret.",chinese:"利用命题 2.E.1–2.E.3 证明 pᵀDₚx(p,w)p=-w，并解释。",tests:"把 Cournot 加总矩阵式右乘 p，再用瓦尔拉斯法则。",hints:["Cournot：pᵀDₚx=-xᵀ。","两边右乘 p。"],solution:["由 Cournot 加总 pᵀDₚx=-xᵀ，右乘 p 得 pᵀDₚxp=-xᵀp。瓦尔拉斯法则给 xᵀp=w，故结果为 -w。","解释：所有价格沿当前价格向量同比小幅上升时，按原价格加权的需求变化恰好抵消当前总支出；与零次齐次下财富同步调整相呼应。教学参考解，非官方答案。"],source:"MWG 原 PDF 60 / 印刷 36"},
 {id:"MWG-2.E.7",lectureId:"L02",lessonId:"L02-M02",number:"2.E.7",difficulty:"A",status:"ready",original:"A consumer in a two-good economy has a demand function x(p,w) that satisfies Walras' law. His demand function for the first good is x₁(p,w)=aw/p₁. Derive his demand function for the second good. Is his demand function homogeneous of degree zero?",chinese:"二商品经济中 x₁=aw/p₁ 且满足瓦尔拉斯法则。求 x₂，并检验零次齐次。",tests:"从预算恒等式补出另一个需求，并同步缩放检查。",hints:["代入 p₁x₁+p₂x₂=w。","检查 (αp,αw)。"],solution:["代入得 aw+p₂x₂=w，所以 x₂=(1-a)w/p₂（非负消费通常还需 0≤a≤1）。","x₁(αp,αw)=aαw/(αp₁)=x₁，x₂ 同理，故零次齐次。教学参考解，非官方答案。"],source:"MWG 原 PDF 61 / 印刷 37"},
 {id:"MWG-2.F.6",lectureId:"L02",lessonId:"L02-M07",number:"2.F.6",difficulty:"A",status:"ready",original:"Suppose that x(p,w) is homogeneous of degree zero. Show that the weak axiom holds if and only if for some w>0 and all p,p′ we have p′·x(p,w)>w whenever p·x(p′,w)≤w and x(p′,w)≠x(p,w).",chinese:"设需求零次齐次。证明：WARP 等价于只在某个固定财富 w>0 上，对所有价格做交叉可负担检验。",tests:"用零次齐次把任意两个财富水平归一化到同一 w。",hints:["WARP⇒固定 w 是直接限制。","反向把 (p⁰,w⁰) 缩放为 (wp⁰/w⁰,w)。"],solution:["必要性：WARP 对所有价格财富对成立，当然对任一固定 w 的子集成立。","充分性：给任意 (p⁰,w⁰)、(p¹,w¹)，分别按正比例 w/w⁰、w/w¹ 缩放价格和财富。零次齐次保证需求束不变，且交叉预算不等式在正比例缩放后保持方向。固定财富条件于是给出所需反向严格不可负担，故一般 WARP 成立。教学参考解。"],source:"MWG 原 PDF 62 / 印刷 38"},
 {id:"MWG-2.F.17",lectureId:"L02",lessonId:"L02-M14",number:"2.F.17",difficulty:"B",status:"ready",original:"In an L-commodity world, xₖ(p,w)=w/(∑_{ℓ=1}^L pℓ), k=1,…,L. (a) Is it homogeneous of degree zero? (b) Does it satisfy Walras' law? (c) Does it satisfy the weak axiom? (d) Compute the Slutsky matrix. Is it negative semidefinite? Negative definite? Symmetric?",chinese:"L 商品世界中每种商品需求都为 w/价格总和。依次检验零次齐次、瓦尔拉斯法则、WARP，并计算与判定 Slutsky 矩阵。",tests:"综合使用本讲四类限制；区分负半定、负定与对称。",hints:["记 P=∑pℓ。","Slutsky 补偿后 w′=qP′。","计算 ∂xℓ/∂pₖ 与 ∂xℓ/∂w。"],solution:["(a) 分子分母同乘 α，比值不变，故零次齐次。(b) ∑pₖxₖ=(w/P)P=w。","(c) 令初始 q=w/P。补偿到 p′ 时 w′=p′·x=qP′，故 x(p′,w′)=q·1=x，补偿需求不变；结合零次齐次和瓦尔拉斯法则满足 WARP。","(d) ∂xℓ/∂pₖ=-w/P²，∂xℓ/∂w=1/P，xₖ=w/P，所以 sℓk=0。S 为零矩阵：负半定、非负定、对称。教学参考解，非官方答案。"],source:"MWG 原 PDF 63 / 印刷 39；需求公式已按原页图像核对"}
];
