const S = (pages, note = "") => ({ sourceId: "L04", file: "New Slides 4(3).pdf", pdfPages: pages, note });
const P = (id, prompt, hint, answer) => ({ id, prompt, hint, answer });

export const lecture4 = {
  id:"L04",title:"需求对偶关系与福利度量",originalTitle:"Preferences and Utility",status:"ready",pptPages:28,
  description:"Shephard 与 Roy、Slutsky 方程、EV/CV、面积近似和无谓损失。",
  lessons:[
    {id:"L04-M01",sectionId:"L04-S01",title:"EMP 的 KKT 条件与 UMP 对照",minutes:13,status:"ready",sourceRefs:[S([1],"MWG In-text 3.E.1 见原 PDF 85 / 印刷 61")],why:"第四讲从严格凸偏好下的单值 x 与 h 开始；先把 EMP 一阶条件写全，才能看清两个问题的乘子只差归一化。",concept:["EMP 在 u(x)≥ū、x≥0 下最小化 p·x。可微时存在 λ≥0，使 p≥λ∇u(x*)，且 x*·[p-λ∇u(x*)]=0；同时效用约束在课程条件下取等。","UMP 条件是 ∇u(x*)≤μp，x*·[∇u(x*)-μp]=0。内点时 EMP 给 p=λ∇u，UMP 给 ∇u=μp，所以正则情形 λ=1/μ，二者都给 MRS=价格比。"],formal:["p≥λ∇u(x*)","x*·[p-λ∇u(x*)]=0"],demo:{prompt:"为什么两个问题的乘子不能直接写成同一个数？",steps:["UMP 把预算放进拉格朗日函数，乘子量纲是效用/货币。","EMP 把效用约束放入目标，乘子量纲是货币/效用；内点时互为倒数。"]},practice:P("P-L04-M01","若 xℓ*>0，EMP 的第 ℓ 个条件变成什么？","互补项中 xℓ*>0。","必须 pℓ=λ∂u(x*)/∂xℓ；若 xℓ*=0，只要求 pℓ≥λ∂u/∂xℓ。"),exerciseIds:["MWG-3.E.1"]},
    {id:"L04-M02",sectionId:"L04-S01",title:"包络定理与 Shephard 引理",minutes:12,status:"ready",sourceRefs:[S([2])],why:"支出函数对价格的导数直接等于 Hicks 需求；最优束随价格变化的间接项被一阶条件消掉。",concept:["支出函数 e(p,u)=p·h(p,u)。包络定理对价格求偏导时，只保留目标对参数的直接效应，因此 ∇ₚe(p,u)=h(p,u)。","它不是把 h 当常数粗暴求导；h 的变化项与约束乘子项由最优性条件抵消。可微和单值是写成普通梯度等式的重要条件。"],formal:["h(p,u)=∇ₚe(p,u)"],demo:{prompt:"∂e/∂pℓ 的经济含义是什么？",steps:["价格 pℓ 小幅增加 dpℓ。","达到同一效用的最低支出一阶增加 hℓdpℓ，所以导数是补偿需求量。"]},practice:P("P-L04-M02","若 e(p,u)=u√(p₁p₂)，写出 h₁。","对 p₁ 求偏导。","h₁=(u/2)√(p₂/p₁)。")},
    {id:"L04-M03",sectionId:"L04-S01",title:"支出 Hessian：对称、负半定与价格零方向",minutes:12,status:"ready",sourceRefs:[S([3])],why:"Shephard 引理把 Hicks 价格导数变成支出函数 Hessian，因此一次得到替代矩阵的三项结构。",concept:["Dₚh=D²ₚe。e 关于价格凹，所以 Hessian 负半定；二阶偏导在正则条件下可交换，所以 Dₚh 对称。","h 对价格零次齐次，由 Euler 公式 Dₚh·p=0。价格同比缩放只换计价单位，不改变补偿需求。"],formal:["Dₚh=D²ₚe ⪯0","Dₚh=(Dₚh)ᵀ","Dₚh·p=0"],demo:{prompt:"为什么 Dₚh 不可能负定？",steps:["它有非零向量 p 满足 Dₚh·p=0。","因此 pᵀDₚhp=0，不能对所有非零方向严格为负。"]},practice:P("P-L04-M03","对称性依赖什么正则性？","混合二阶偏导何时可交换？","需要 e 对价格足够光滑（通常二次连续可微）；非光滑点应使用次梯度/对应表述。"),review:{id:"R-L04-01",prompt:"Dₚh 的三项结构是什么？",answer:"它等于支出函数关于价格的 Hessian，因此对称、负半定，并满足 Dₚh·p=0。"}},
    {id:"L04-M04",sectionId:"L04-S02",title:"Hicks 替代品与互补品",minutes:9,status:"ready",sourceRefs:[S([4])],why:"这里的替代/互补按补偿需求交叉导数定义，不能与普通需求的交叉价格效应混用。",concept:["若 ∂hℓ/∂pk≥0，商品 ℓ、k 是 Hicks 替代品；若 ≤0，称互补品。对称性给 ∂hℓ/∂pk=∂hk/∂pℓ。","由 Dₚh·p=0、p≫0 且自身效应≤0，每种商品至少要有一个非负交叉项来平衡其自身项（允许弱等号）。"],formal:["替代: ∂hℓ/∂pk≥0；互补: ∂hℓ/∂pk≤0"],demo:{prompt:"交叉项为0时属于哪类？",steps:["按弱不等式定义，它同时满足替代与互补。","经济上可称补偿意义下独立，避免把弱分类理解为互斥。"]},practice:P("P-L04-M04","普通需求 ∂xℓ/∂pk>0 能否直接推出 Hicks 替代？","Slutsky 方程还有财富项。","不能；必须扣除/加入财富效应后看 ∂hℓ/∂pk。")},
    {id:"L04-M05",sectionId:"L04-S03",title:"Slutsky 方程：沿对偶恒等式做链式法则",minutes:14,status:"ready",sourceRefs:[S([5])],why:"Slutsky 方程不是记忆公式；它来自 h(p,u)=x[p,e(p,u)] 对价格求导。",concept:["固定 u，对 hℓ(p,u)=xℓ[p,e(p,u)] 关于 pk 求导：直接价格效应加上财富变化引起的间接效应。","再用 Shephard ∂e/∂pk=hk，并在 u=v(p,w) 时 h=x、e=w，得到 ∂hℓ/∂pk=∂xℓ/∂pk+(∂xℓ/∂w)xk。矩阵式 Dₚh=S。"],formal:["∂hℓ/∂pk=∂xℓ/∂pk+(∂xℓ/∂w)xk","Dₚh(p,v(p,w))=S(p,w)"],demo:{prompt:"公式右侧为什么乘 xk 而不是 xℓ？",steps:["pk 变化1单位时，Slutsky 补偿原束需要 xk 单位财富。","这笔财富通过商品 ℓ 的财富效应 ∂xℓ/∂w 改变其需求。"]},practice:P("P-L04-M05","若商品 ℓ 无财富效应，普通与 Hicks 自身价格斜率怎样？","令 ∂xℓ/∂w=0。","二者相等：∂hℓ/∂pℓ=∂xℓ/∂pℓ。")},
    {id:"L04-M06",sectionId:"L04-S03",title:"正常品、劣等品与两条需求曲线",minutes:12,status:"ready",sourceRefs:[S([6,7,8])],why:"同一价格变化下，普通需求既含替代效应又含实际财富效应；必须区分‘数量对价格的响应’与纵价横量图上的几何斜率。",concept:["自身项满足 ∂hℓ/∂pℓ=∂xℓ/∂pℓ+(∂xℓ/∂w)xℓ。正常品的财富效应≥0，所以在通常负导数情形下，普通需求的 |∂x/∂p| 更大：同一小价格变化引起的数量响应更强。这里比较的是横量作为价格函数的导数，不直接叫图上更陡。","课件图以价格 p 为纵轴、数量 x 为横轴。若局部可逆且导数非零，图上斜率是 dp/dx=1/(dx/dp)。例如普通需求 dx/dp=-5、Hicks 需求 dh/dp=-2 时，图上斜率分别为 -1/5、-1/2，反而是 Hicks 曲线更陡。零导数或不可逆处不能机械取倒数。","劣等品的财富效应<0 时数量响应的排序反向；Giffen 情形是普通自身价格效应变为正。每个结论都要先说明比较的是导数、绝对响应还是图上斜率。"],demo:{prompt:"为什么‘数量响应更大’不等于纵价横量图上更陡？",steps:["数量响应看 dx/dp 的绝对值。","纵价横量图看反函数斜率 dp/dx；在局部可逆且导数非零时，它是前者的倒数。","因此 |dx/dp| 越大，|dp/dx| 反而越小，图线更平。"]},practice:P("P-L04-M06","正常品有 ∂h/∂p=-2、财富项 (∂x/∂w)x=3，普通价格效应是多少？在纵价横量图上哪条局部更陡？","先由 Hicks=普通+财富项求 dx/dp，再在导数非零时取倒数。","∂x/∂p=-2-3=-5。数量响应上普通需求更强；图上 dp/dx=-1/5，Hicks 为 dp/dh=-1/2，所以 Hicks 曲线局部更陡。")},
    {id:"L04-M07",sectionId:"L04-S04",title:"有限补偿与局部等价不能混写",minutes:12,status:"ready",sourceRefs:[S([9,10,11])],why:"Hicks 与 Slutsky 的有限财富补偿一般不同；它们只在起点的一阶变化中一致。",concept:["有限变化时 e(p′,u)≤p′·x(p,w)，因为原束只是达到 u 的一个候选，未必最便宜，所以 Δw_H≤Δw_S。","小价格变化的一阶展开给 de=∇ₚe·dp=h·dp=x·dp，正好等于 Slutsky 补偿的一阶式。于是 Dₚh=S 在一点成立，并把对称性传给理性偏好生成的 Slutsky 矩阵。","第二讲仅由零次齐次、Walras 法则和 WARP 得到负半定与零方向，不能推出对称；对称来自效用最大化/支出函数的积分结构。"],demo:{prompt:"为什么有限 Δw 相等不能由导数相等推出？",steps:["导数只描述起点附近的一阶项。","沿有限路径，Hicks 束持续调整，原束计价不再跟随最低支出路径。"]},practice:P("P-L04-M07","写出小变化时共同的一阶补偿额。","用起点需求点积价格变化。","d w_H=d w_S=x(p,w)ᵀdp。"),review:{id:"R-L04-02",prompt:"Hicks 与 Slutsky 补偿何时相等？",answer:"一般有限变化不相等；在共同起点 h(p,u)=x(p,w) 附近的一阶微分相等，都是 xᵀdp。"}},
    {id:"L04-M08",sectionId:"L04-S05",title:"Roy 恒等式：先检查分母，再用财富导数归一化",minutes:13,status:"ready",sourceRefs:[S([12,13],"普通比值形式要求间接效用在该点可微且财富偏导非零；参见 MWG 印刷第55页脚注10的非退化条件")],why:"普通需求不能直接等于 ∇ₚv，因为效用只具序数意义；只有在财富偏导存在且非零时，才能用它归一化。",concept:["从 v[p,e(p,u)]=u 对 p 求导：∇ₚv+(∂v/∂w)∇ₚe=0。代入 ∇ₚe=h=x；若 ∂v/∂w≠0，才可相除得到 Roy 比值。","严格递增或局部非饱和本身不保证每一点的 ∂v/∂w 都严格为正。严格递增函数可以在某点导数为0；因此普通公式还需要可微与非退化梯度条件。分母为0、v 不可微或需求多值时，不能直接使用这个普通导数比值。","若把 u 换成可微且导数非零的严格递增变换 f(u)，v 的价格与财富导数同乘 f′，比值不变；这说明 Roy 恢复的是需求而非效用刻度。"],formal:[{tex:"x_\\ell(p,w)=-\\frac{\\partial v(p,w)/\\partial p_\\ell}{\\partial v(p,w)/\\partial w},\\qquad \\frac{\\partial v}{\\partial w}\\ne0"}],demo:{prompt:"为什么‘财富增加能改善’仍不能省略分母非零条件？",steps:["偏好上的严格改善是序数陈述，导数是所选效用表示的局部数值性质。","例如严格递增的三次函数在拐点导数可为0；相应间接效用的财富偏导也可在该点为0。","所以先核对可微与 ∂v/∂w≠0，再进行除法。"]},practice:P("P-L04-M08","若 v=ln w-ln p₁，Roy 给 x₁ 多少？本例分母为何可除？","算两个偏导并先检查 v_w。","v_{p₁}=-1/p₁，v_w=1/w>0，所以分母非零，x₁=-v_{p₁}/v_w=w/p₁。")},
    {id:"L04-M09",sectionId:"L04-S05",title:"综合算例：从效用到 x、h、e、v",minutes:18,status:"ready",sourceRefs:[S([12,13],"配套 MWG 3.G.15 原 PDF 125 / 印刷 101；效用公式已按图像核对")],why:"一题贯通 UMP、EMP、Shephard 和 Roy，能暴露公式下标、平方根与归一化中的错误。",concept:["原题效用 u=2√x₁+4√x₂，严格凹且单调。记 D=p₂+4p₁。普通需求为 x₁=wp₂/[p₁D]、x₂=4wp₁/[p₂D]。","Hicks 需求 h₁=u²p₂²/[4D²]、h₂=u²p₁²/D²；支出 e=u²p₁p₂/[4D]。间接效用 v=2√[wD/(p₁p₂)]。对 e 求价格梯度恢复 h，对 v 用 Roy 恢复 x。"],formal:["D=p₂+4p₁","e(p,u)=u²p₁p₂/[4D]","v(p,w)=2√(wD/(p₁p₂))"],demo:{prompt:"怎样快速检查 e 与 v 互逆？",steps:["把 w=e(p,u) 代入 v。","根号内化为 u²/4，得到 v=u（取非负效用域）。"]},practice:P("P-L04-M09","对 e 关于 p₁ 求导应得到什么？","对 p₁p₂/(p₂+4p₁) 用商法则。","得到 u²p₂²/[4(p₂+4p₁)²]=h₁。"),exerciseIds:["MWG-3.G.15"]},
    {id:"L04-M10",sectionId:"L04-S06",title:"货币度量效用：选一组参考价格",minutes:10,status:"ready",sourceRefs:[S([14,15])],why:"直接效用差依赖表示选择；货币度量把两个效用水平都换成在同一参考价格下所需财富。",concept:["给定参考价格 p̄，货币度量值是 e[p̄,v(p,w)]。因为 e(p̄,·) 严格递增，它保持福利排序，同时单位是货币。","福利变化 e(p̄,u₁)-e(p̄,u₀) 的大小依赖参考价格 p̄；它不是脱离基准的唯一金额。自然选择是变化前或变化后的价格，对应 EV 与 CV。"],demo:{prompt:"为什么换效用表示不会改变货币度量结果？",steps:["支出函数的效用标签随表示一起重标。","达到同一偏好等级的最小支出不变。"]},practice:P("P-L04-M10","参考价格改变后福利排序会改变吗？金额会改变吗？","e 对效用严格递增。","对同一两效用水平，排序不变；金额差一般会变。")},
    {id:"L04-M11",sectionId:"L04-S06",title:"EV 与 CV：严格沿用课件符号",minutes:13,status:"ready",sourceRefs:[S([16,17],"本站沿用课件 EV/CV 方向；其他教材可能采用相反号")],why:"EV/CV 最易错在参考价格和正负号。先固定 u₀=v(p⁰,w)、u₁=v(p¹,w)，再代定义。",concept:["课件定义 EV=e(p⁰,u₁)-e(p⁰,u₀)=e(p⁰,u₁)-w：在旧价格下，多少收入变化等价于价格变化。","CV=e(p¹,u₁)-e(p¹,u₀)=w-e(p¹,u₀)：变化已发生后，需要多少收入变化补偿。按此约定，若价格上涨使福利下降，EV、CV 通常为负，-EV 是阻止变化的最大支付，-CV 是接受变化所需最小补偿。"],formal:["EV=e(p⁰,u₁)-w","CV=w-e(p¹,u₀)"],demo:{prompt:"为何先写 u₀、u₁ 能减少符号错误？",steps:["每个支出项的价格基准和效用目标一目了然。","再用 e(p⁰,u₀)=e(p¹,u₁)=w 化简，不靠口号猜正负。"]},practice:P("P-L04-M11","若价格变化提高福利，按课件约定 EV、CV 倾向什么符号？","u₁>u₀，e 对效用递增。","二者倾向为正；它们表示等价/补偿的收入增加方向。")},
    {id:"L04-M12",sectionId:"L04-S06",title:"拟线性偏好为何有 CV=EV",minutes:14,status:"ready",sourceRefs:[S([16,17],"配套 MWG 3.I.5 原 PDF 126 / 印刷 102；I 为字母")],why:"拟线性消除相关财富效应，使参考旧价或新价得到相同福利金额。",concept:["对商品1拟线性且 p₁=1，在非负约束不绑定的标准域内，间接效用可写 v(p,w)=w+ψ(p)，支出函数为 e(p,u)=u-ψ(p)。","于是 u₀=w+ψ(p⁰)、u₁=w+ψ(p¹)。EV=u₁-ψ(p⁰)-w=ψ(p¹)-ψ(p⁰)；CV=w-[u₀-ψ(p¹)] 也是同一差。"],proof:{known:"u=x₁+φ(x₋₁)，p₁=1，拟线性域内财富只进入计价商品。",goal:"按课件定义证明 CV=EV。",steps:["写 v(p,w)=w+ψ(p)。","由 v 与 e 互逆得 e(p,u)=u-ψ(p)。","分别代入 EV=e(p⁰,u₁)-w 与 CV=w-e(p¹,u₀)。","两者都化为 ψ(p¹)-ψ(p⁰)。"],assumptions:"若 x₁≥0 约束绑定，拟线性财富独立性可能局部失效；原题按标准拟线性消费集和 p₁=1。"},practice:P("P-L04-M12","这里 CV=EV 的根本原因是价格不变吗？","价格可以变；看财富效应。","不是。根本原因是拟线性结构使相关需求无财富效应，货币度量差不依赖选旧价还是新价。"),exerciseIds:["MWG-3.I.5"],review:{id:"R-L04-03",prompt:"课件约定下 EV 与 CV 分别用哪组参考价格？",answer:"EV 用变化前价格 p⁰；CV 用变化后价格 p¹。"}},
    {id:"L04-M13",sectionId:"L04-S07",title:"Hicks 面积、普通需求面积与排序",minutes:14,status:"ready",sourceRefs:[S([18,19,20,21,22,23])],why:"单一商品价格变化时，EV/CV 可写成两条 Hicks 曲线下的积分；普通需求面积 AV 位于两者之间。",concept:["仅商品 ℓ 从 pℓ⁰ 变为 pℓ¹，EV=∫_{p¹}^{p⁰}hℓ(pℓ,p₋ℓ,u₁)dpℓ，CV=∫_{p¹}^{p⁰}hℓ(pℓ,p₋ℓ,u₀)dpℓ。积分方向沿用课件定义。","AV=∫_{p¹}^{p⁰}xℓ(pℓ,p₋ℓ,w)dpℓ。价格下降且商品正常时 CV≤AV≤EV；劣等品时 EV≤AV≤CV；无财富效应时三者相等。结论依赖图示的单价变化与商品类型条件。"],formal:["AV=∫_{pℓ¹}^{pℓ⁰}xℓ(pℓ,p₋ℓ,w)dpℓ"],demo:{prompt:"为什么正常品时高效用 Hicks 需求更大？",steps:["达到 u₁ 需要的支出不低于达到 u₀。","正常品随财富增加需求不减，因此 h(p,u₁)≥h(p,u₀)。"]},practice:P("P-L04-M13","无财富效应时三条需求为何重合？","Slutsky 财富项为0。","普通与 Hicks 需求对价格的斜率相同且在起点相交，故相关路径重合，AV=CV=EV。")},
    {id:"L04-M14",sectionId:"L04-S07",title:"AV 何时是好近似",minutes:10,status:"ready",sourceRefs:[S([24,25])],why:"‘面积近似福利’不是普遍定理；误差小需要财富效应小或价格变化小，并警惕多商品误差累积。",concept:["单个商品财富效应小时，普通需求与两条 Hicks 需求接近，AV 近似 EV/CV。商品很多时单项财富效应可能分散，但多个价格同时变化会把许多小误差累积。","价格变化足够小时，曲线间狭长区域相对主面积变小，AV 的一阶近似改善；这不意味着任何有限变化都可忽略收入效应。"],demo:{prompt:"多商品为何既可能帮助又可能伤害近似？",steps:["单个价格变化时，财富效应分散到许多商品，目标商品误差可能小。","若很多价格同时变，多个小误差相加可能仍大。"]},practice:P("P-L04-M14","‘小价格变化’保证 AV 与 EV 完全相等吗？","近似与精确要分开。","不保证；通常只说误差相对更小或一阶近似一致，除非财富效应确为零等特殊条件。")},
    {id:"L04-M15",sectionId:"L04-S08",title:"从单位税到无谓损失与近似误差",minutes:15,status:"ready",sourceRefs:[S([26,27,28])],why:"单位税造成的福利损失要和筹得税收比较；用普通需求近似时，误差相对 DWL 未必随小税率消失。",concept:["商品 ℓ 加单位税 t，使 pℓ¹=pℓ⁰+t，税收 T=t·xℓ(p¹,w)。课件符号下 DWL=-EV-T，可写成 Hicks 需求相对税后数量的积分，非负。","直观上，一次性税若筹同样 T，不扭曲边际价格；单位税多损失 Hicks 曲线与税后数量矩形之间的面积。用普通需求构造 DWL_AV 会多出财富效应区域 C。虽然绝对误差随 t 变小，C/B 未必趋零，因此不能自动宣称相对误差消失。"],formal:["DWL=-EV(p⁰,p¹,w)-T","T=t·xℓ(p¹,w)"],demo:{prompt:"为什么证明 DWL≥0 用 Hicks 自身需求法则？",steps:["Hicks 需求随自身价格非增。","积分区间内需求不低于税后端点数量，所以曲线减矩形高度的被积函数非负。"]},practice:P("P-L04-M15","税率很小时，AV 近似 EV 好，是否必然意味着 AV-DWL 的相对误差小？","福利变化是一阶，DWL 常是二阶小量。","不必然。DWL 本身更小，近似误差与它可能同阶，所以误差/DWL 未必趋零。"),review:{id:"R-L04-04",prompt:"课件符号下单位税的 DWL 怎样定义？",answer:"DWL=-EV-T，其中 T=t·xℓ(p¹,w) 是税收；等价于 Hicks 需求曲线与税后数量矩形之间的非负面积。"}}
  ]
};

export const lecture4Exercises=[
  {id:"MWG-3.E.1",lectureId:"L04",lessonId:"L04-M01",number:"3.E.1",difficulty:"A",status:"ready",original:"Assume that u(·) is differentiable. Show that the first-order conditions for the EMP are p ≥ λ∇u(x*) and x*·[p-λ∇u(x*)]=0, for some λ≥0. Compare this with the first-order conditions of the UMP.",chinese:"设效用可微，推导 EMP 的价格-梯度不等式与互补条件，并和 UMP 一阶条件比较。",tests:"正确设置效用与非负约束；区分内点等式、角点不等式及两个乘子的量纲。",hints:["把约束写成 u(x)-ū≥0 与 x≥0。","内点商品的非负约束乘子为0。","UMP 条件可写 ∇u≤μp。"],solution:["取最小化问题的拉格朗日条件。对效用约束乘子 λ≥0，并处理 x≥0，可得每个分量 pℓ≥λuℓ(x*)；若 xℓ*>0 则等号。合并为 p≥λ∇u(x*) 与 x*·[p-λ∇u(x*)]=0。另有可行性、效用约束互补；课程条件下达到效用目标恰取等。","UMP 对应 ∇u(x*)≤μp、x*·[∇u(x*)-μp]=0。内点时 EMP 为 p=λ∇u，UMP 为 ∇u=μp，因此 λ=1/μ，并都推出 MRS=价格比。教学参考解，非官方答案。"],source:"MWG 正文原 PDF 85 / 印刷 61；公式按原页图像核对"},
  {id:"MWG-3.G.15",lectureId:"L04",lessonId:"L04-M09",number:"3.G.15",difficulty:"B",status:"ready",original:"Consider u=2x₁^(1/2)+4x₂^(1/2). (a) Find Walrasian demands. (b) Find compensated demand h. (c) Find expenditure and verify h(p,u)=∇ₚe(p,u). (d) Find indirect utility and verify Roy's identity.",chinese:"对 u=2√x₁+4√x₂，依次求普通需求、Hicks 需求、支出函数与间接效用，并验证 Shephard 引理和 Roy 恒等式。",tests:"完整贯通 UMP/EMP 两组一阶条件与两个包络恒等式。",hints:["记 D=p₂+4p₁。","UMP 比较 (1/√x₁)/(2/√x₂)=p₁/p₂。","EMP 中令 2√x₁+4√x₂=u 取等。"],solution:["记 D=p₂+4p₁。UMP 一阶条件给 √x₂=2(p₁/p₂)√x₁，结合预算得 x₁=wp₂/[p₁D]、x₂=4wp₁/[p₂D]。","EMP 得 √h₁=λ/p₁、√h₂=2λ/p₂，效用约束给 λ=up₁p₂/[2D]。因此 h₁=u²p₂²/[4D²]、h₂=u²p₁²/D²，e=p₁h₁+p₂h₂=u²p₁p₂/[4D]。直接求导可得 e_{p₁}=h₁、e_{p₂}=h₂。","代普通需求入效用得 v=2√[wD/(p₁p₂)]=2√[w(1/p₁+4/p₂)]。计算 -v_{p₁}/v_w=wp₂/[p₁D]=x₁，-v_{p₂}/v_w=4wp₁/[p₂D]=x₂，验证 Roy。教学参考解，非官方答案。"],source:"MWG 原 PDF 125 / 印刷 101；效用公式按原页图像核对"},
  {id:"MWG-3.I.5",lectureId:"L04",lessonId:"L04-M12",number:"3.I.5",difficulty:"B",status:"ready",original:"Show that if u(x) is quasilinear with respect to the first good (and we fix p₁=1), then CV(p⁰,p¹,w)=EV(p⁰,p¹,w) for any (p⁰,p¹,w).",chinese:"若效用对第一种商品拟线性并固定 p₁=1，证明任意价格变化下 CV=EV。",tests:"用拟线性间接效用与支出函数形式，严格遵循本课 EV/CV 符号。",hints:["写 v(p,w)=w+ψ(p)。","由互逆关系写 e(p,u)=u-ψ(p)。","分别代入课件定义。"],solution:["拟线性且计价品价格 p₁=1 时，在标准消费域内 v(p,w)=w+ψ(p)，所以 e(p,u)=u-ψ(p)。令 u₀=w+ψ(p⁰)、u₁=w+ψ(p¹)。","EV=e(p⁰,u₁)-w=u₁-ψ(p⁰)-w=ψ(p¹)-ψ(p⁰)。CV=w-e(p¹,u₀)=w-u₀+ψ(p¹)=ψ(p¹)-ψ(p⁰)。故 CV=EV。若计价品非负约束绑定，需另查适用区间。教学参考解。"],source:"MWG 原 PDF 126 / 印刷 102；题号 I 为大写字母"}
];
